controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

send_invoice:
    path: /send-invoice
    controller: App\Controller\StagiaireController::sendInvoice
